### ISSUE TITLE
There is literally zero styling

### ISSUE THREAD

**Issue by HardcoreParkore** [HardcoreParkore/espn-ff-web#9]
This is kind of higher priority because I think having a good user experience is important for our league to actually adopt doing their submissions weekly.

What I want for this project is (in this order)

* Something we don't have to spend a lot of time on (unless someone is dying to go all designer on us)
* Something that's easy to follow. I *think* I like the idea of css-in-js libraries, but I haven't used one yet. I honestly just love the concept of writing style for one component and not needing to dig into where a single css file applies to whatever class happens to be floating around somewhere in the app.

I think this leads us to using something like material-bootstrap in the short term so we can ship with a decent UI or have one within a week or two of shipping this power ranking feature, but I haven't figured that out yet.

**Comment by GabrielFabian** [comment]
https://react-bootstrap.github.io/getting-started/introduction/

**Comment by GabrielFabian** [comment]
This is probably our best bet. React bootstrap make developing a _halfway_ decent ui pretty simple.

**Comment by HardcoreParkore** [comment]
Began implementing material-ui across the codebase
